// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Server.Client", b =>
                {
                    b.Property<string>("tcpClient")
                        .HasColumnType("TEXT");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ipAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("port")
                        .HasColumnType("INTEGER");

                    b.HasKey("tcpClient");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
